# Generated by Django 5.2.7 on 2025-10-14 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('επιθετο', models.CharField(db_index=True, help_text='Το επώνυμο του πολίτη', max_length=100, verbose_name='Επίθετο')),
                ('ονομα', models.CharField(db_index=True, help_text='Το όνομα του πολίτη', max_length=100, verbose_name='Όνομα')),
                ('πατρωνυμο', models.CharField(blank=True, max_length=100, verbose_name='Πατρώνυμο')),
                ('συσταση_απο', models.CharField(blank=True, db_index=True, help_text='Ποιος σύστησε τον πολίτη', max_length=200, verbose_name='Σύσταση Από')),
                ('κινητο', models.CharField(blank=True, help_text='Μορφή: 6912345678 ή +306912345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Εισάγετε έγκυρο ελληνικό τηλέφωνο (10 ψηφία, π.χ. 2310123456 ή 6912345678)', regex='^(\\+30)?[2-9][0-9]{9}$')], verbose_name='Κινητό Τηλέφωνο')),
                ('σταθερο', models.CharField(blank=True, help_text='Μορφή: 2310123456 ή +302310123456', max_length=20, validators=[django.core.validators.RegexValidator(message='Εισάγετε έγκυρο ελληνικό τηλέφωνο (10 ψηφία, π.χ. 2310123456 ή 6912345678)', regex='^(\\+30)?[2-9][0-9]{9}$')], verbose_name='Σταθερό Τηλέφωνο')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email')),
                ('διευθυνση', models.CharField(blank=True, help_text='Οδός και αριθμός', max_length=300, verbose_name='Διεύθυνση')),
                ('τκ', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Εισάγετε έγκυρο 5ψήφιο ΤΚ', regex='^[0-9]{5}$')], verbose_name='ΤΚ')),
                ('δημος', models.CharField(blank=True, choices=[('ΠΑΥΛΟΥ_ΜΕΛΑ', 'Παύλου Μελά'), ('ΚΟΡΔΕΛΙΟΥ_ΕΥΟΣΜΟΥ', 'Κορδελίου-Ευόσμου'), ('ΑΜΠΕΛΟΚΗΠΩΝ_ΜΕΝΕΜΕΝΗΣ', 'Αμπελοκήπων-Μενεμένης'), ('ΝΕΑΠΟΛΗΣ_ΣΥΚΕΩΝ', 'Νεάπολης-Συκεών'), ('ΘΕΣΣΑΛΟΝΙΚΗΣ', 'Θεσσαλονίκης'), ('ΚΑΛΑΜΑΡΙΑΣ', 'Καλαμαριάς'), ('ΑΛΛΟ', 'Άλλο')], db_index=True, max_length=50, verbose_name='Δήμος')),
                ('περιοχη', models.CharField(blank=True, max_length=100, verbose_name='Περιοχή')),
                ('εκλογικη_περιφερεια', models.CharField(blank=True, choices=[('Α_ΘΕΣΣΑΛΟΝΙΚΗΣ', "Α' Θεσσαλονίκης"), ('Β_ΘΕΣΣΑΛΟΝΙΚΗΣ', "Β' Θεσσαλονίκης"), ('ΑΛΛΟ', 'Άλλο')], db_index=True, max_length=50, verbose_name='Εκλογική Περιφέρεια')),
                ('κατηγορια_επαφης', models.CharField(choices=[('GDPR', 'GDPR'), ('ΑΙΤΗΜΑ', 'Αίτημα'), ('GDPR_ΚΑΙ_ΑΙΤΗΜΑ', 'GDPR και Αίτημα')], db_index=True, default='GDPR', max_length=50, verbose_name='Κατηγορία Επαφής')),
                ('ιδιοτητα', models.CharField(blank=True, db_index=True, help_text='π.χ. Φοιτητής, Συνταξιούχος, Επιχειρηματίας', max_length=100, verbose_name='Ιδιότητα')),
                ('ημερομηνια_προσθηκης', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Προσθήκης')),
                ('παρατηρησεις', models.TextField(blank=True, verbose_name='Παρατηρήσεις')),
                ('is_active', models.BooleanField(default=True, help_text='Αποεπιλέξτε για να αρχειοθετήσετε (soft delete)', verbose_name='Ενεργός')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Αρχειοθετήθηκε στις')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
                ('αρμοδιος_συνεργατης', models.ForeignKey(blank=True, help_text='Ποιος χειρίζεται αυτόν τον πολίτη', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_citizens', to=settings.AUTH_USER_MODEL, verbose_name='Αρμόδιος Συνεργάτης')),
            ],
            options={
                'verbose_name': 'Πολίτης',
                'verbose_name_plural': 'Πολίτες',
                'ordering': ['-ημερομηνια_προσθηκης'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ημερομηνια_επικοινωνιας', models.DateField(db_index=True, help_text='Πότε έγινε η επικοινωνία', verbose_name='Ημερομηνία Επικοινωνίας')),
                ('τυπος', models.CharField(choices=[('ΤΗΛΕΦΩΝΟ', 'Τηλεφώνημα'), ('EMAIL', 'Email'), ('ΠΡΟΣΩΠΙΚΗ', 'Προσωπική Επίσκεψη'), ('SMS', 'SMS'), ('ΑΛΛΟ', 'Άλλο')], default='ΤΗΛΕΦΩΝΟ', max_length=20, verbose_name='Τύπος Επικοινωνίας')),
                ('σημειωσεις', models.TextField(blank=True, help_text='Τι συζητήθηκε / τι ειπώθηκε', verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Καταχωρήθηκε στις')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Καταχωρήθηκε από')),
                ('πολιτης', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='citizens.citizen', verbose_name='Πολίτης')),
            ],
            options={
                'verbose_name': 'Επικοινωνία',
                'verbose_name_plural': 'Επικοινωνίες',
                'ordering': ['-ημερομηνια_επικοινωνιας', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('κατηγορια_αιτηματος', models.CharField(choices=[('ΣΤΡΑΤΙΩΤΙΚΟ', 'Στρατιωτικό'), ('ΙΑΤΡΙΚΟ', 'Ιατρικό'), ('ΑΣΤΥΝΟΜΙΚΟ', 'Αστυνομικό'), ('ΠΥΡΟΣΒΕΣΤΙΚΗ', 'Πυροσβεστική'), ('ΠΑΙΔΕΙΑΣ', 'Παιδείας'), ('ΔΙΟΙΚΗΤΙΚΟ', 'Διοικητικό'), ('ΕΥΡΕΣΗ_ΕΡΓΑΣΙΑΣ', 'Εύρεση Εργασίας'), ('ΕΦΚΑ', 'ΕΦΚΑ'), ('ΑΛΛΟ', 'Άλλο')], db_index=True, max_length=30, verbose_name='Κατηγορία Αιτήματος')),
                ('κατασταση', models.CharField(choices=[('ΟΛΟΚΛΗΡΩΜΕΝΟ', 'Ολοκληρωμένο'), ('ΜΗ_ΟΛΟΚΛΗΡΩΜΕΝΟ', 'Μη Ολοκληρωμένο'), ('ΕΚΚΡΕΜΕΙ', 'Εκκρεμεί')], db_index=True, default='ΕΚΚΡΕΜΕΙ', max_length=30, verbose_name='Κατάσταση')),
                ('ημερομηνια_αποστολης', models.DateField(blank=True, db_index=True, help_text='Πότε στάλθηκε το αίτημα', null=True, verbose_name='Ημερομηνία Αποστολής')),
                ('ημερομηνια_ολοκληρωσης', models.DateField(blank=True, help_text='Πότε ολοκληρώθηκε το αίτημα', null=True, verbose_name='Ημερομηνία Ολοκλήρωσης')),
                ('αιτημα_κειμενο', models.TextField(help_text='Αναλυτική περιγραφή του αιτήματος', verbose_name='Αίτημα')),
                ('παρατηρησεις', models.TextField(blank=True, verbose_name='Παρατηρήσεις')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Υπενθύμιση Στάλθηκε')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Στάλθηκε υπενθύμιση στις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('πολιτης', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='citizens.citizen', verbose_name='Πολίτης')),
            ],
            options={
                'verbose_name': 'Αίτημα',
                'verbose_name_plural': 'Αιτήματα',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilitaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('τυπος', models.CharField(choices=[('ΣΤΡΑΤΙΩΤΗΣ', 'Στρατιώτης'), ('ΜΟΝΙΜΟΣ', 'Μόνιμος')], help_text='Στρατιώτης ή Μόνιμος', max_length=20, verbose_name='Τύπος')),
                ('ονομα', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('επωνυμο', models.CharField(max_length=100, verbose_name='Επώνυμο')),
                ('πατρωνυμο', models.CharField(blank=True, max_length=100, verbose_name='Πατρώνυμο')),
                ('ημερομηνια_αποστολης', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Αποστολής')),
                ('παρατηρησεις', models.TextField(blank=True, verbose_name='Παρατηρήσεις')),
                ('εσσο_ετος', models.CharField(blank=True, help_text='π.χ. 2025', max_length=4, validators=[django.core.validators.RegexValidator(message='4ψήφιο έτος', regex='^[0-9]{4}$')], verbose_name='ΕΣΣΟ Έτος')),
                ('εσσο_γραμμα', models.CharField(blank=True, choices=[('Α', 'Α'), ('Β', 'Β'), ('Γ', 'Γ'), ('Δ', 'Δ'), ('Ε', 'Ε'), ('ΣΤ', 'ΣΤ')], max_length=2, verbose_name='ΕΣΣΟ Γράμμα')),
                ('ασμ', models.CharField(blank=True, help_text='Αριθμός Στρατολογικού Μητρώου', max_length=50, verbose_name='ΑΣΜ')),
                ('επιθυμια', models.CharField(blank=True, max_length=200, verbose_name='Επιθυμία')),
                ('κεντρο', models.CharField(blank=True, max_length=200, verbose_name='Κέντρο')),
                ('ημερομηνια_παρουσιασης', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Παρουσίασης')),
                ('τοποθετηση', models.CharField(blank=True, max_length=200, verbose_name='Τοποθέτηση')),
                ('ημερομηνια_τοποθετησης', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Τοποθέτησης')),
                ('μεταθεση_αποσπαση', models.CharField(blank=True, max_length=200, verbose_name='Μετάθεση/Απόσπαση')),
                ('ημερομηνια_μεταθεσης', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Μετάθεσης')),
                ('βαθμος', models.CharField(blank=True, max_length=100, verbose_name='Βαθμός')),
                ('μοναδα_υπηρεσιας', models.CharField(blank=True, max_length=200, verbose_name='Μονάδα Υπηρεσίας')),
                ('επιθυμια_μονιμου', models.CharField(blank=True, max_length=200, verbose_name='Επιθυμία')),
                ('σχολια', models.TextField(blank=True, verbose_name='Σχόλια')),
                ('αμ', models.CharField(blank=True, max_length=50, verbose_name='ΑΜ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε στις')),
                ('αιτημα', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='military_details', to='citizens.request', verbose_name='Αίτημα')),
            ],
            options={
                'verbose_name': 'Στρατιωτικό Αίτημα',
                'verbose_name_plural': 'Στρατιωτικά Αιτήματα',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['επιθετο', 'ονομα'], name='citizens_ci_επιθετο_c087bc_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['δημος', 'εκλογικη_περιφερεια'], name='citizens_ci_δημος_896343_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['-ημερομηνια_προσθηκης'], name='citizens_ci_ημερομη_b7d733_idx'),
        ),
        migrations.AddConstraint(
            model_name='citizen',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('επιθετο', 'ονομα', 'κινητο'), name='unique_active_citizen'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['-ημερομηνια_επικοινωνιας'], name='citizens_co_ημερομη_fdd44a_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['κατασταση', '-ημερομηνια_αποστολης'], name='citizens_re_καταστα_9844f4_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['κατηγορια_αιτηματος', 'κατασταση'], name='citizens_re_κατηγορ_8d4b2f_idx'),
        ),
    ]
