# Generated by Django 5.2.7 on 2025-10-30 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MilitaryPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "τυπος",
                    models.CharField(
                        choices=[("ΣΤΡΑΤΙΩΤΗΣ", "Στρατιώτης"), ("ΜΟΝΙΜΟΣ", "Μόνιμος")],
                        db_index=True,
                        help_text="Στρατιώτης ή Μόνιμος",
                        max_length=20,
                        verbose_name="Τύπος",
                    ),
                ),
                (
                    "επωνυμο",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Επώνυμο"
                    ),
                ),
                (
                    "ονομα",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Όνομα"
                    ),
                ),
                (
                    "πατρωνυμο",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Πατρώνυμο"
                    ),
                ),
                (
                    "κινητο",
                    models.CharField(
                        blank=True,
                        help_text="Μορφή: 6912345678",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Εισάγετε έγκυρο ελληνικό τηλέφωνο (10 ψηφία)",
                                regex="^(\\+30)?[2-9][0-9]{9}$",
                            )
                        ],
                        verbose_name="Κινητό Τηλέφωνο",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "εσσο_ετος",
                    models.CharField(
                        blank=True,
                        help_text="π.χ. 2025",
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="4ψήφιο έτος", regex="^[0-9]{4}$"
                            )
                        ],
                        verbose_name="ΕΣΣΟ Έτος",
                    ),
                ),
                (
                    "εσσο_γραμμα",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Α", "Α"),
                            ("Β", "Β"),
                            ("Γ", "Γ"),
                            ("Δ", "Δ"),
                            ("Ε", "Ε"),
                            ("ΣΤ", "ΣΤ"),
                        ],
                        max_length=2,
                        verbose_name="ΕΣΣΟ Γράμμα",
                    ),
                ),
                (
                    "ασμ",
                    models.CharField(
                        blank=True,
                        help_text="Αριθμός Στρατολογικού Μητρώου",
                        max_length=50,
                        verbose_name="ΑΣΜ",
                    ),
                ),
                (
                    "επιθυμια",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Επιθυμία Στρατιώτη"
                    ),
                ),
                (
                    "κεντρο",
                    models.CharField(blank=True, max_length=200, verbose_name="Κέντρο"),
                ),
                (
                    "ημερομηνια_παρουσιασης",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ημερομηνία Παρουσίασης"
                    ),
                ),
                (
                    "τοποθετηση",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Τοποθέτηση"
                    ),
                ),
                (
                    "ημερομηνια_τοποθετησης",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ημερομηνία Τοποθέτησης"
                    ),
                ),
                (
                    "μεταθεση_αποσπαση",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Μετάθεση/Απόσπαση"
                    ),
                ),
                (
                    "ημερομηνια_μεταθεσης",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ημερομηνία Μετάθεσης"
                    ),
                ),
                (
                    "βαθμος",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Βαθμός"
                    ),
                ),
                (
                    "μοναδα_υπηρεσιας",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Μονάδα Υπηρεσίας"
                    ),
                ),
                (
                    "επιθυμια_μονιμου",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Επιθυμία Μόνιμου"
                    ),
                ),
                (
                    "αμ",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ΑΜ (Αριθμός Μητρώου)"
                    ),
                ),
                (
                    "παρατηρησεις",
                    models.TextField(blank=True, verbose_name="Παρατηρήσεις"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Δημιουργήθηκε στις"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ενημερώθηκε στις"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_military_personnel",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Δημιουργήθηκε από",
                    ),
                ),
                (
                    "αρμοδιος_συνεργατης",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_military_personnel",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Αρμόδιος Συνεργάτης",
                    ),
                ),
                (
                    "πολιτης",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="military_personnel",
                        to="citizens.citizen",
                        verbose_name="Πολίτης",
                    ),
                ),
            ],
            options={
                "verbose_name": "Στρατιωτικό Προσωπικό",
                "verbose_name_plural": "Στρατιωτικό Προσωπικό",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="MilitaryRequest",
        ),
        migrations.AddIndex(
            model_name="militarypersonnel",
            index=models.Index(
                fields=["τυπος", "επωνυμο"], name="citizens_mi_τυπος_6237f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="militarypersonnel",
            index=models.Index(
                fields=["εσσο_ετος", "εσσο_γραμμα"],
                name="citizens_mi_εσσο_ετ_71e8de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="militarypersonnel",
            index=models.Index(
                fields=["-created_at"], name="citizens_mi_created_e07347_idx"
            ),
        ),
    ]
