# Generated by Django 5.2.7 - Sync help_text fields (no database changes)

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration exists to sync model help_text with the database state.
    help_text doesn't affect the database schema, so this is a no-op migration.
    """

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        # No database operations - just marking models as in sync
    ]
